export const DEFAULT_OFFER_COUNT = 60;
export const DEFAULT_PREMIUM_OFFER_COUNT = DEFAULT_OFFER_COUNT;
export const DEFAULT_FAVORITE_OFFER_COUNT = DEFAULT_OFFER_COUNT;
export const PRICE_MAX_DECIMAL_PLACES = 2;
export const RATING_MAX_DECIMAL_PLACES = 1;
